apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: reverse-proxy
  region: us-east-1

nodeGroups:
  - name: reverse-proxy
    labels: { role: reverse-proxy }
    instanceType: t3.micro
    desiredCapacity: 2
    privateNetworking: true
  